Aad 729 reminder notifications
SkillsFundingAgency/das-apprentice-progress-api pull request #17
Opened 2024-12-12 12:54 UTC by CathyGroom

add new endpoint for getting task reminders by apprentice

2024-12-12 16:42 UTC, alireid commented on src/SFA.DAS.ApprenticeProgress.Application/Tasks/Queries/GetTaskRemindersByApprenticeshipId/GetTaskRemindersByApprenticeshipIdHandler.cs
> +
Tidy

2024-12-12 17:00 UTC, CathyGroom commented on src/SFA.DAS.ApprenticeProgress.Application/Tasks/Queries/GetTaskRemindersByApprenticeshipId/GetTaskRemindersByApprenticeshipIdHandler.cs
> +
I also modified the Where clauses slightly to only include ToDo tasks and to only exclude Dismissed reminders.

2024-12-13 09:29 UTC, alireid approved these changes

2024-12-13 09:34 UTC, alireid approved these changes

2024-12-16 14:16 UTC, alireid approved these changes
Visually looks great

2024-12-16 14:17 UTC, alireid requested changes
Coverage...

2024-12-16 15:43 UTC, alireid approved these changes

2024-12-16 15:45 UTC, merged